// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PixelPerfect","status":true,"description":"Adjustments and options for different resolutions.","parameters":{"tileWidth":"48","tileHeight":"48","imageFileTag":"_DISABLED","useTextImages":"false","textImages":"","balloonW":"48","balloonH":"48","buttonW":"48","buttonH":"48","iconW":"32","iconH":"32","faceW":"144","faceH":"144","stateW":"96","stateH":"96","weaponW":"96","weaponH":"64","sideViewActorW":"64","sideViewActorH":"64"}}
];
