// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PixelPerfect","status":true,"description":"Adjustments and options for different resolutions.","parameters":{"tileSize":"16","useTextImages":"false","textImages":"","iconW":"32","iconH":"32"}}
];
