// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RetroPixels","status":true,"description":"Adjustments and options for retro-style graphics","parameters":{"retroPixelSize":"3"}},
{"name":"FlexibleWindows","status":true,"description":"Adjustments and options for default and custom windows","parameters":{"useRetroPixelSize":"false","windowsSettings":"[\"{\\\"window\\\":\\\"MenuBase Help\\\",\\\"customWindowName\\\":\\\"\\\",\\\"hidden\\\":\\\"false\\\",\\\"relativePosition\\\":\\\"true\\\",\\\"x\\\":\\\"0\\\",\\\"y\\\":\\\"0\\\",\\\"relativeSize\\\":\\\"true\\\",\\\"width\\\":\\\"0\\\",\\\"height\\\":\\\"0\\\"}\"]"}}
];
